CREATE TABLE Users (
	ID INT NOT NULL PRIMARY KEY ON CONFLICT REPLACE AUTOINCREMENT,
	Username TEXT NOT NULL,
	Password TEXT NOT NULL
);

CREATE TABLE Links (
	UserID INT NOT NULL,
	Name TEXT NOT NULL,
	Target TEXT NOT NULL,
	Public BOOLEAN NOT NULL CHECK(Public BETWEEN 0 AND 1) DEFAULT 0,
	PRIMARY KEY (UserID, Name) ON CONFLICT REPLACE
);

-- key:value solution instead
CREATE TABLE Links (
	Name TEXT NOT NULL PRIMARY KEY ON CONFLICT REPLACE,
	Target TEXT NOT NULL
);
